#/bin/bash
echo > ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.storage-driver-id=S3" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.type=s3" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.label=S3" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.bucket-name=${aws_bucket_name}" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.download-redirect=true" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.upload-redirect=true" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.url-expiration-minutes=120" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.connection-pool-size=4096" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.profile=${aws_s3_profile}" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logStandardStreams=true" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "set-log-attributes com.sun.enterprise.server.logging.GFFileHandler.logtoFile=true" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
keyid=$(grep 'access key' $aws_config | awk -F ': ' {'print $2'};)
secret_key=$(grep 'secret' $aws_config | awk -F ': ' {'print $2'};)
endpoint=$aws_endpoint_url
echo "create-system-properties dataverse.files.S3.access-key="$keyid >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.secret-key="$secret_key >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.S3.custom-endpoint-url=$endpoint" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#V5.13
echo "create-system-properties dataverse.files.uploads=/opt/payara/appserver/glassfish/domains/domain1/uploads" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.siteUrl="'https\:\/\/'${hostname} >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.files.directory=/tmp/dataverse">> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.rserve.port=6311" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.rserve.user=rserve" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.rserve.password=rserve" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.rserve.tempdir=/tmp/Rserv" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.pid.datacite.mds-api-url=${baseurlstring}" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.pid.datacite.rest-api-url=${dataciterestapiurlstring}" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.pid.datacite.username=${doi_username}" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.pid.datacite.password=${doi_password}" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.handlenet.key.path=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.handlenet.key.passphrase=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
echo "create-system-properties dataverse.pid.handlenet.index=300" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.permalink.base-url="'https\:\/\/'${hostname} >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.ezid.api-url="'https\:\/\/'${hostname} >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.ezid.username=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.ezid.password=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.signposting.level1-author-limit=12" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.signposting.level1-item-limit=12" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.api.allow-incomplete-metadata="'https\:\/\/'${hostname} >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.ui.show-validity-filter=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.ui.allow-review-for-incomplete=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.spi.export.directory=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.mail.support-email=support@dataverse.no" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.mail.cc-support-on-contact-emails=support@dataverse.no" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.netcdf.geo-extract-s3-direct-upload=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.ezid.password=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.ezid.password=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
#echo "create-system-properties dataverse.pid.ezid.password=test" >> ${INIT_SCRIPTS_FOLDER}/preboot.payara
