truncate table dvnoaffiliations;
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('1', 'The Norwegian Police University College', 'phs.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('2', 'University of Agder', 'uia.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('3', 'NIFU', 'nifu.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('4', 'Østfold University College', 'hiof.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('5', 'The Oslo School of Architecture and Design', 'aho.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('6', 'Chr. Michelsen Institute', 'cmi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('7', 'MF Norwegian School of Theology, Religion and Society', 'mf.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('8', 'Queen Maud University College', 'dmmh.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('9', 'Norwegian School of Economics', 'nhh.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('10', 'NLA University College', 'nla.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('11', 'Norwegian Polar Institute', 'npolar.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('12', 'Norwegian Computing Center', 'nr.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('13', 'SINTEF', 'sintef.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('14', 'Sámi allaskuvla – Sámi University College', 'samiskhs.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('15', 'University of Bergen', 'uib.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('16', 'University of Oslo', 'uio.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('17', 'UiT The Arctic University of Norway', 'uit.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('18', 'Norwegian University of Science and Technology', 'ntnu.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('19', 'Norwegian Institute for Nature Research', 'nina.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('20', 'Geological Survey of Norway', 'ngu.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('21', 'Molde University College', 'himolde.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('22', 'National Library of Norway', 'nb.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('23', 'University of Stavanger', 'uis.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('24', 'Volda University College', 'hivolda.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('25', 'Oslo National Academy of the Arts', 'khio.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('26', 'Institute for Social Research', 'samfunnsforskning.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('27', 'Lovisenberg Diaconal University College', 'ldh.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('28', 'Norwegian Institute of Public Health', 'fhi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('29', 'Norwegian School of Sport Sciences', 'nih.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('30', 'BI Norwegian Business School', 'bi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('31', 'Norwegian Academy of Music', 'nmh.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('32', 'Kristiania University College', 'kristiania.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('33', 'Norwegian Defence University College', 'fhs.mil.no', '3');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('34', 'Ansgar University College', 'ansgarskolen.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('35', 'OsloMet – Oslo Metropolitan University', 'oslomet.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('36', 'Norwegian University of Life Sciences', 'nmbu.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('37', 'Norwegian Institute of Bioeconomy Research', 'nibio.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('38', 'VID Specialized University', 'vid.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('39', 'Nord University', 'nord.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('40', 'University of South-Eastern Norway', 'usn.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('41', 'Western Norway University of Applied Sciences', 'hvl.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('42', 'Norwegian centre for violence and traumatic stress studies', 'nkvts.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('43', 'Inland Norway University of Applied Sciences', 'inn.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('44', 'Norwegian Veterinary Institute', 'vetinst.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('45', 'NUBU - The Norwegian Center for Child Behavioral Development', 'nubu.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('46', 'The Norwegian Center for Holocaust and Minority Studies', 'hlsenteret.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('47', 'Norwegian Meteorological Institute', 'met.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('48', 'Simula Research Laboratory', 'simula.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('49', 'Agder Research', 'agderforskning.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('50', 'Akvaplan-niva', 'akvaplan.niva.no', '3');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('51', 'Norwegian Labour Movement Archives and Library', 'arbark.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('52', 'Centre for Advanced Study', 'cas.oslo.no', '3');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('53', 'CICERO Center for International Climate Research', 'cicero.oslo.no', '3');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('54', 'Christian Michelsen Research', 'cmr.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('55', 'nan', 'dataverse.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('56', 'nan', 'DataverseNO Admin', '1');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('57', 'nan', 'DataverseNO Curator', '1');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('58', 'nan', 'DataverseNO Dataset Creator', '1');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('59', 'Diakonova', 'diakonova.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('60', 'Fafo Foundation', 'fafo.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('61', 'Norwegian Defence Research Establishment', 'ffi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('62', 'Flymedisinsk institutt', 'flymed.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('63', 'Fridtjof Nansen Institute', 'fni.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('64', 'GenØk – Centre for Biosafety', 'genok.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('65', 'Norwegian Institute of Marine Research', 'hi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('66', 'Institute for Energy Technology', 'ife.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('67', 'International Research Institute of Stavanger', 'iris.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('68', 'Institute for Church, Religion, and Worldview Research', 'kifo.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('69', 'Cancer Registry of Norway', 'kreftregisteret.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('70', 'nan', 'legeforeningen.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('71', 'Møreforsking', 'moreforsk.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('72', 'Nansen Environmental and Remote Sensing Center', 'nersc.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('73', 'Aeromedical Center of Norway', 'nfms.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('74', 'Nordland Research Institute', 'nforsk.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('75', 'Norwegian Geotechnical Institute', 'ngi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('76', 'Norwegian Institute for Cultural Heritage Research', 'niku.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('77', 'Norwegian Institute for Air Research', 'nilu.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('78', 'Norwegian Institute for Water Research', 'niva.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('79', 'Norsk Landbruksrådgiving', 'nlr.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('80', 'Norwegian Nobel Institute', 'nobel.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('81', 'Nofima', 'nofima.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('82', 'Norwegian Research Centre', 'norceresearch.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('83', 'Norwegian Seismic Array', 'norsar.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('84', 'Norsk senter for økologisk landbruk', 'norsok.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('85', 'Norwegian Institute for Sustainability Research', 'norsus.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('86', 'nan', 'norut.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('87', 'Norwegian Institute of International Affairs', 'nupi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('88', 'Ostfold Research', 'ostfoldforskning.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('89', 'Eastern Norway Research Institute', 'ostforsk.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('90', 'Paper and Fibre Research Institute', 'pfi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('91', 'Peace Research Institute', 'prio.org', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('92', 'RISE Fire Research', 'risefr.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('93', 'Institute for Rural and Regional Research', 'ruralis.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('94', 'Centre for Intercultural Communication', 'sik.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('95', 'Centre for Applied Research', 'snf.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('96', 'National Institute of Occupational Health', 'stami.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('97', 'Teknova', 'teknova.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('98', 'Tel-Tek', 'tel-tek.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('99', 'Trøndelag Forskning og Utvikling', 'tfou.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('100', 'TISIP', 'tisip.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('101', 'Telemark Research Institute', 'tmforsk.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('102', 'Institute of Transport Economics', 'toi.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('103', 'Norwegian Institute of Wood Technology', 'treteknisk.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('104', 'Uni Research', 'uni.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('105', 'Western Norway Research Institute', 'vestforsk.no', '2');
insert into dvnoaffiliations (id, dvno_affiliation, dvno_group_name, dvno_email_level) values ('106', 'Westerdals Oslo School of Arts, Communication and Technology', 'westerdals.no', '2');
